language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
before_install:
  - "export DISPLAY=:99.0"
  - "export CODECLIMATE_REPO_TOKEN=f965fda6d493fe7c6d3e3358a9ea39f2b6bad21bf837fc2c2e41a2aaa3bf4cd2 "
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - "bundle exec rake test_app"
script:
  - "bundle exec rake"
notifications:
  email:
    - luke@madetech.co.uk
    - seb@madetech.co.uk
branches:
  only:
    - master
